name: Thread Sanitizer

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tsan:
    name: TSan
    runs-on: ubuntu-latest
    container:
      image: helics/buildenv:sanitizers-19

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Mark workspace as safe for git
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Configure
        run: cmake -S . -B build -DCMAKE_CXX_FLAGS="-fsanitize=thread -g -O1 -Wno-reserved-macro-identifier"

      - name: Build
        run: cmake --build build --parallel 4

      - name: Test
        working-directory: build
        run: TSAN_OPTIONS="second_deadlock_stack=1 suppressions=$PWD/../config/tsan_suppression.txt history_size=4" ctest --verbose
